-- +goose Up
CREATE TABLE tag (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255),
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO tag (name) VALUES ('tag1');
INSERT INTO tag (name) VALUES ('tag2');
